name: parallel_map_wf
namespace: workflows
description: |
  Map RNA sequencing data, provided as fastq files (paired-end) to a reference genome using STAR Solo.
  Input data must have been demultiplexed beforehand, meaning that a single fastq pair provides data for
  one barcode (one well). Multiple wells can be mapped in parallel by providing multiple events to the 
  workflow. Output is provided as mapped output per pool, i.e. one output is provided per pool.
authors:
  - __merge__: /src/base/authors/dries_schaumont.yaml
    roles: [ maintainer ]
argument_groups:
  - name: "Input arguments"
    arguments:
      - name: "--input_r1"
        type: file
        direction: input
        required: true
        multiple: true
      - name: "--input_r2"
        type: file
        direction: input
        multiple: true
        required: true
      - name: "--barcodesFasta"
        type: file
        required: true
      - name: "--umi_length"
        type: integer
        min: 1
      - name: "--genomeDir"
        type: file
        required: true
        direction: input
  - name: "Output arguments"
    arguments:
      - name: "--output"
        type: file
        direction: output
        multiple: true
        required: true
resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf

# test_resources:
#   - type: nextflow_script
#     path: test.nf
#     entrypoint: test_wf

dependencies:
  - name: parallel_map
    repository: local
repositories:
  - name: local
    type: local

runners:
  - type: nextflow

engines:
  - type: native

