name: create_report
namespace: "report"
description: |
  Create a basic QC report in HTML format based on a number of esets.
authors:
  - __merge__: /src/base/authors/dries_schaumont.yaml
    roles: [ maintainer ]
  - __merge__: /src/base/authors/marijke_van_moerbeke.yaml
    roles: [ author, maintainer ]
argument_groups:
  - name: "Arguments"
    arguments:
    - type: file
      name: "--eset"
      required: true
      multiple: true
    - type: file
      name: "--preproc_params"
    - type: file
      name: "--output_report"
      required: true
      direction: output
      example: report.html
resources:
  - type: r_script
    path: script.R
  - type: r_script
    path: template.Rmd
  - type: r_script
    path: plateLayouts.R
  - path: OutputSTARsolo.png 
    type: file
test_resources:
  - type: r_script
    path: test.R
  - path: ./test_data
engines:
  - type: docker
    image: rocker/r2u:26.04
    setup:
      # This avoids an issue with nextflow https://github.com/nextflow-io/nextflow/issues/7114
      # that is caused by a bug in the rust implementation of coreutils. This will be fixed
      # in a future release of Ubuntu: see https://bugs.launchpad.net/ubuntu/+source/rust-coreutils/+bug/2150342
      # To check if the fix has been released, compare the output from `date +%s%3N` and
      # `gnudate +%s%3N` in a fresh `rocker/r2u:26.04` container.
      # The output should have the same number of digits in case the fix has been applied.
      - type: docker
        run: |
          apt update && \
            DEBIAN_FRONTEND=noninteractive apt install -y coreutils-from-gnu coreutils-from-uutils- --allow-remove-essential && \
            rm -rf /var/lib/apt/lists/*
      - type: apt
        packages:
          - procps
          - pandoc
      - type: r
        bioc:
          - Biobase
          - ComplexHeatmap
        cran:
          - ggplot2
          - knitr
          - gridExtra
          - RColorBrewer
          - processx
          - whisker
          - rmarkdown
          - bookdown
          - data.table
          - platetools
          - htmltools
          - DT
          - logger
          - bit64
          - yaml
        script:
          - install.packages("oaStyle", repos = c(rdepot = "https://repos.openanalytics.eu/repo/public", getOption("repos")))
    test_setup:
      - type: r
        packages:
          - testthat
          - R.utils
runners:
  - type: executable
  - type: nextflow