name: save_params
namespace: utils
description: |
  Save parameters to a file

argument_groups:
  - name: Inputs
    arguments:
      - name: "--id"
        description: |
          The id of the job
        type: string
        required: true
      - name: "--params"
        description: |
          The state to save
        type: string
        multiple: true
        required: true
    
  - name: Outputs
    arguments:
      - name: "--output"
        description: |
          The output file
        type: string
        required: true

resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: python:3.12-slim
    setup:
      - type: apt
        packages:
          - procps
      - type: python
        packages:
          - pyyaml

runners:
  - type: executable
  - type: nextflow