name: runner
namespace: workflows
description: Runner for HT RNA-seq pipeline
argument_groups:
  - name: Input arguments
    arguments:
      - name: --input
        description: Base directory of the form `s3:/<bucket>/Sequencing/<Sequencer>/<RunID>/`
        type: file
        required: true
      - name: --barcodesFasta
        type: file
        required: true
      - name: --genomeDir
        type: file
        required: true
      - name: --annotation
        type: file
        required: true
  - name: Annotation flags
    arguments:
      - name: --add_date_time
        description: |
          Add date and time to the output directory name. This is useful
          when running the same pipeline multiple times on the same input
          directory.
        type: boolean_true
      - name: --add_workflow_id
        description: |
          Add a workflow identifier to the output directory name.
        type: boolean_true
  - name: Output arguments
    arguments:
      - name: --fastq_output_r1
        description: List of demultiplexed fastq files
        type: file
        direction: output
        multiple: true
        required: true
        default: "fastq/*_R1_001.fastq"
      - name: --fastq_output_r2
        description: List of demultiplexed fastq files
        type: file
        direction: output
        multiple: true
        required: true
        default: "fastq/*_R2_001.fastq"
      - name: --star_output
        description: Output from mapping with STAR
        type: file
        direction: output
        multiple: true
        required: true
        default: $id/star/*
      - name: "--nrReadsNrGenesPerChrom"
        type: file
        direction: output
        required: true
        default: "nrReadsNrGenesPerChrom.$id.txt"
      - name: "--star_qc_metrics"
        type: file
        direction: output
        required: true
        default: "starLogs.$id.txt"
      - name: "--eset"
        type: file
        direction: output
        required: true
        default: eset.$id.rds
      - name: "--f_data"
        type: file
        direction: output
        required: true
        default: fData.$id.tsv
      - name: "--p_data"
        type: file
        direction: output
        required: true
        default: pData.$id.tsv
      - name: "--html_report"
        type: file
        direction: output
        required: true
        default: report.html

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf

dependencies:
  - name: utils/listInputDir
    repository: local
  - name: workflows/htrnaseq
    repository: local
  - name: io/publish_fastqs
    repository: local

runners:
  - type: nextflow

engines:
  - type: native
