name: groupPairs
namespace: workflows/utils
description: |
  N/A
argument_groups:
  - name: Inputs
    arguments:
      - name: "--input"
        type: file
        description: Path to the input for R1
        required: true
        example: input.fastq.gz

  - name: Output
    arguments:
      - name: "--r1"
        type: file
        description: Path to output for R2
        required: true
        direction: output
      - name: "--r2"
        type: file
        description: Path to output for R2
        required: true
        direction: output
resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf

runners:
  - type: nextflow
