name: create_fdata
namespace: eset
description: |
  Create a fdata file
arguments:
- name: "--gtf"
  type: file
  description: "Genome annotation file in GTF format."
  required: true
- name: "--output"
  description: |
    Tab-delimited text file containing information about the 'gene' or 'transcript'
    entries from the input GTF file. The 'transcript' entries are used in case the source
    of the GTF was 'refGene' or 'ncbiRefSeq'. 
  type: file
  direction: output
  default: fData.$id.txt
resources:
- type: python_script
  path: create_fdata.py
test_resources:
- type: python_script
  path: test.py
- path: test_annotation.gtf
engines:
  - type: docker
    image: python:3.12-slim
    setup:
      - type: apt
        packages:
          - procps
      - type: python
        packages:
          - pandas
    test_setup:
      - type: python
        packages:
          - viashpy
runners:
  - type: executable
  - type: nextflow